#!/usr/bin/env python

# Ensure we are running Python3 
import sys
if sys.version_info[0] < 3:
    raise Exception("Must be using Python 3")

import claid_manager

if __name__ == "__main__":
    claid_manager.init()
